# Generated by Django 5.0 on 2023-12-28 21:07

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotentRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("key", models.CharField(max_length=256, unique=True)),
                ("response_body", models.TextField()),
                ("response_headers", models.JSONField()),
                ("response_status", models.IntegerField()),
            ],
        ),
    ]
