# Generated by Django 5.0 on 2023-12-27 22:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('account_type', models.CharField(choices=[('system', 'System'), ('checking', 'Checking'), ('loans_receivable', 'Loans receivable'), ('credit_card', 'Credit card'), ('discount_allowed', 'Discount allowed')], default='Checking', max_length=16)),
                ('normal', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')])),
                ('balance', models.IntegerField(default=0)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_entries', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_entries', to='accounting.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date_close', models.DateTimeField()),
                ('balance', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
