# Generated by Django 5.0 on 2023-12-13 01:07

import accounting.models.mixins
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normal", models.IntegerField(choices=[(1, "Debit"), (-1, "Credit")])),
            ],
            bases=(
                accounting.models.mixins.IdentifiableMixin,
                accounting.models.mixins.TimestampedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_effective", models.DateTimeField()),
            ],
            bases=(
                accounting.models.mixins.IdentifiableMixin,
                accounting.models.mixins.TimestampedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="JournalEntryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("normal", models.IntegerField(choices=[(1, "Debit"), (-1, "Credit")])),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounting.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounting.journalentry",
                    ),
                ),
            ],
            bases=(
                accounting.models.mixins.IdentifiableMixin,
                accounting.models.mixins.TimestampedMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_close", models.DateTimeField()),
                ("balance", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounting.account",
                    ),
                ),
            ],
            bases=(
                accounting.models.mixins.IdentifiableMixin,
                accounting.models.mixins.TimestampedMixin,
                models.Model,
            ),
        ),
    ]
