# Generated by Django 5.0 on 2023-12-25 16:16

import accounting.models.mixins
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
            bases=(accounting.models.mixins.IdentifiableMixin, accounting.models.mixins.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField()),
            ],
            bases=(accounting.models.mixins.IdentifiableMixin, accounting.models.mixins.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('system', 'System'), ('checking', 'Checking'), ('loans_receivable', 'Loans receivable'), ('credit_card', 'Credit card'), ('discount_allowed', 'Discount allowed')], default='Checking', max_length=16)),
                ('normal', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')])),
                ('balance', models.IntegerField()),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountholder')),
            ],
            bases=(accounting.models.mixins.IdentifiableMixin, accounting.models.mixins.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal', models.IntegerField(choices=[(1, 'Debit'), (-1, 'Credit')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.journalentry')),
            ],
            bases=(accounting.models.mixins.IdentifiableMixin, accounting.models.mixins.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_close', models.DateTimeField()),
                ('balance', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.account')),
            ],
            bases=(accounting.models.mixins.IdentifiableMixin, accounting.models.mixins.TimestampedMixin, models.Model),
        ),
    ]
